name: Copy file to another repository

on:
  workflow_dispatch:
    inputs:
      source_file:
        description: "Path of the file to copy from source repo"
        required: true
        default: "notes.txt"

      target_repo:
        description: "Target repository (OWNER/REPO)"
        required: true
        default : aitmansouraziz/Git_Tuturial_01

      target_branch:
        description: "Target branch"
        required: true
        default: "main"

      target_path:
        description: "Destination path in target repo"
        required: true
        default: "./Ressources/notes.txt"

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.target_repo }}
          ref: ${{ inputs.target_branch }}
          token: ${{ secrets.TARGET_REPO_TOKEN }}
          path: target-repo

      - name: Commit and push changes
        run: |
          cd target-repo
          git config user.name "aitmansouraziz"
          git config user.email "mansour.aziz@hotmail.com"
          git add "${{ inputs.target_path }}"
          git commit -m "Copy ${{ inputs.source_file }} from source repository" || echo "No changes to commit"
          git push
